#!/usr/bin/env bash
# Agent Stack bootstrap for Arch Linux — bash port of install.ps1.
# Run from repo root on a new machine: ./install.sh
# Idempotent: safe to re-run (skills skip existing, env append is guarded,
# patches apply only if --check passes).
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TS="$(date +%Y%m%d-%H%M%S)"
BACKUP_BASE="/tmp/opencode/agent-stack-backup-$TS"

copy_tree() {
    local src="$1" dst="$2"
    if [ ! -d "$src" ]; then echo "missing: $src"; return 0; fi
    mkdir -p "$dst"
    cp -r "$src/." "$dst/"
    echo "  copied -> $dst"
}

backup() {
    local path="$1"
    if [ -e "$path" ]; then
        local b="$BACKUP_BASE/$(echo "$path" | tr '/' '_')"
        mkdir -p "$BACKUP_BASE"
        cp -r "$path" "$b"
        echo "  backup of $path -> $b"
    fi
}

echo "== agent-stack setup (arch) =="

# 0. backups (herdr integrations live inside these dirs; reinstalled at the end)
backup "$HOME/.pi/agent"
backup "$HOME/.config/opencode"

# 1. pi config
copy_tree "$REPO/config/pi" "$HOME/.pi/agent"
# agents dir lives one level up from agent/
mkdir -p "$HOME/.pi/agents"
cp -f "$REPO/config/pi/agents/"* "$HOME/.pi/agents/" 2>/dev/null || true

# 2. opencode config
copy_tree "$REPO/config/opencode" "$HOME/.config/opencode"
# Fix Windows-only playwright profile path -> arch home dir
python3 - "$HOME/.config/opencode/opencode.json" "$HOME" <<'EOF'
import json, sys
path, home = sys.argv[1], sys.argv[2]
with open(path) as f:
    cfg = json.load(f)
try:
    cmd = cfg["mcp"]["user-playwright"]["command"]
    fixed = [c.replace("C:\\Users\\jembo\\Projects\\CVTailor\\.linkedin-profile",
                       f"{home}/Projects/CVTailor/.linkedin-profile") for c in cmd]
    cfg["mcp"]["user-playwright"]["command"] = fixed
    with open(path, "w") as f:
        json.dump(cfg, f, indent=2)
    print("  fixed playwright user-data-dir -> linux path")
except KeyError:
    print("  playwright mcp block not found, skipped path fix")
EOF

# 3. skills (skip existing so local edits survive)
mkdir -p "$HOME/.agents/skills"
for d in "$REPO/skills/"*/; do
    [ -d "$d" ] || continue
    name="$(basename "$d")"
    dst="$HOME/.agents/skills/$name"
    if [ ! -e "$dst" ]; then
        cp -r "$d" "$dst"
        echo "  skill installed: $name"
    else
        echo "  skill exists, skipped: $name"
    fi
done
# opencode-only skills
mkdir -p "$HOME/.config/opencode/skills"
for d in "$REPO/config/opencode-skills/"*/; do
    [ -d "$d" ] || continue
    name="$(basename "$d")"
    dst="$HOME/.config/opencode/skills/$name"
    if [ ! -e "$dst" ]; then
        cp -r "$d" "$dst"
        echo "  oc-skill installed: $name"
    else
        echo "  oc-skill exists, skipped: $name"
    fi
done

# 4. pi packages (npm/package.json is generated by pi itself on first launch
#    from the `packages` list in settings.json)
if [ ! -f "$HOME/.pi/agent/npm/package.json" ]; then
    echo "  NOTE: ~/.pi/agent/npm/package.json missing."
    echo "  Launch pi once (it installs settings.json packages), then re-run ./install.sh"
else
    (cd "$HOME/.pi/agent/npm" && npm install --legacy-peer-deps --no-audit --no-fund)
fi

# 5. patches (see patches/README.md for status)
if command -v git >/dev/null 2>&1; then
    NM="$HOME/.pi/agent/npm/node_modules"
    # pi-cache-optimizer code patch is SUPERSEDED on >=2.8.10 by
    # config/pi/pi-cache-optimizer-config.json (promptCacheKey.omit, copied in step 1).
    co_ver="$(python3 -c "import json;print(json.load(open('$HOME/.pi/agent/npm/node_modules/pi-cache-optimizer/package.json'))['version'])" 2>/dev/null || echo "")"
    omit_cfg="$HOME/.pi/agent/pi-cache-optimizer-config.json"
    if [ -n "$co_ver" ] && [ ! -f "$omit_cfg" ] \
        && [ "$(printf '%s\n' "2.8.10" "$co_ver" | sort -V | head -n1)" != "2.8.10" ]; then
        if git apply --check -p0 "$REPO/patches/pi-cache-optimizer-nvidia-cachekey.patch" --directory="$NM/pi-cache-optimizer" 2>/dev/null; then
            git apply -p0 "$REPO/patches/pi-cache-optimizer-nvidia-cachekey.patch" --directory="$NM/pi-cache-optimizer"
            echo "  patched: pi-cache-optimizer (nvidia cache-key)"
        else
            echo "  patch skipped (already applied or version drift): pi-cache-optimizer"
        fi
    else
        echo "  skip pi-cache-optimizer code patch (native omit config covers >=2.8.10)"
    fi
    # pi-subagents retries patch is RETIRED: upstream 0.68.0 removed fallbackModels
    # and all same-launch model switching, so there is nothing to patch against.
    echo "  skip pi-subagents patch (retired upstream, see patches/README.md)"
else
    echo "  SKIP patches: git not installed (sudo pacman -S --needed git)"
fi

# 5b. git-package patches (reapply after `pi update`)
NIM_DIR="$HOME/.pi/agent/git/github.com/xRyul/pi-nvidia-nim"
if [ -d "$NIM_DIR/.git" ] && command -v git >/dev/null 2>&1; then
    if git -C "$NIM_DIR" apply --check "$REPO/patches/pi-nvidia-nim-glm53-catalog.patch" 2>/dev/null; then
        git -C "$NIM_DIR" apply "$REPO/patches/pi-nvidia-nim-glm53-catalog.patch"
        echo "  patched: pi-nvidia-nim (glm-5.3 catalog)"
    else
        echo "  patch skipped (already applied or version drift): pi-nvidia-nim"
    fi
else
    echo "  skip pi-nvidia-nim patch (extension not installed or git missing)"
fi

# 6. retries env var (shell + login shell; Hyprland GUI apps need hl.env, see note)
for rc in "$HOME/.bashrc" "$HOME/.profile"; do
    [ -f "$rc" ] || continue
    if ! grep -q "PI_SUBAGENT_RETRIES_PER_MODEL" "$rc"; then
        echo 'export PI_SUBAGENT_RETRIES_PER_MODEL=3' >> "$rc"
        echo "  env added to $rc"
    else
        echo "  env already in $rc"
    fi
done

echo ""
echo "Done. Then: source ~/.bashrc; launch pi once to rebuild model registry + auth providers;"
echo "re-run ./install.sh after first pi launch if step 4 was skipped."
echo "If you use Hyprland-launched GUI apps needing this var, add:"
echo '  hl.env("PI_SUBAGENT_RETRIES_PER_MODEL", "3")'
